select
engine_no,
max(operational_setting_1) over w1,
max(operational_setting_2) over w1,
max(operational_setting_3) over w1,
max(sensor_measurement_1) over w1,
max(sensor_measurement_10) over w1,
max(sensor_measurement_11) over w1,
max(sensor_measurement_12) over w1,
max(sensor_measurement_13) over w1,
max(sensor_measurement_14) over w1,
max(sensor_measurement_15) over w1,
max(sensor_measurement_16) over w1,
max(sensor_measurement_17) over w1,
max(sensor_measurement_18) over w1,
max(sensor_measurement_19) over w1,
max(sensor_measurement_2) over w1,
max(sensor_measurement_20) over w1,
max(sensor_measurement_21) over w1,
max(sensor_measurement_3) over w1,
max(sensor_measurement_4) over w1,
max(sensor_measurement_5) over w1,
max(sensor_measurement_6) over w1,
max(sensor_measurement_7) over w1,
max(sensor_measurement_8) over w1,
max(sensor_measurement_9) over w1,
max(operational_setting_1) over w2,
max(operational_setting_2) over w2,
max(operational_setting_3) over w2,
max(sensor_measurement_1) over w2,
max(sensor_measurement_10) over w2,
max(sensor_measurement_11) over w2,
max(sensor_measurement_12) over w2,
max(sensor_measurement_13) over w2,
max(sensor_measurement_14) over w2,
max(sensor_measurement_15) over w2,
max(sensor_measurement_16) over w2,
max(sensor_measurement_17) over w2,
max(sensor_measurement_18) over w2,
max(sensor_measurement_19) over w2,
max(sensor_measurement_2) over w2,
max(sensor_measurement_20) over w2,
max(sensor_measurement_21) over w2,
max(sensor_measurement_3) over w2,
max(sensor_measurement_4) over w2,
max(sensor_measurement_5) over w2,
max(sensor_measurement_6) over w2,
max(sensor_measurement_7) over w2,
max(sensor_measurement_8) over w2,
max(sensor_measurement_9) over w2
from rul_table
window w1 as (partition by engine_no order by record_time rows_range between unbounded preceding and current row),
w2 as (partition by time_in_cycles order by record_time rows_range between unbounded preceding and current row)
;
